
spring:
  #db (change the username and password before run the spring)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 17734614
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useUnicode=true&characterEncoding=utf-8
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
  transaction:
    rollback-on-commit-failure: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  #time zone
  jackson: time-zone=GMT+8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-image-path}
logging:
  level:
    root: info
    pkpd.restaurant: debug

mybatis:
  configuration:
     map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappings/**/*.xml
  type-aliases-package: tk.mybatis.springboot.model
#mapper
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    mapper.not-empty: false
    mapper.identity: MYSQL
#pageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#server information
server:
  port: 8181
  servlet:
    context-path: /restaurant
#web image path (change before run the spring)
web:
  upload-image-path: E:\Programming\Java\Project\restaurant_pos_ultimate\images\restaurant\upload
